# Generated by Django 5.2.3 on 2025-07-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_orders', '0004_alter_order_email_alter_order_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Заказаний товар', 'verbose_name_plural': 'Заказані товари'},
        ),
    ]
