# Generated by Django 5.2.3 on 2025-09-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_orders', '0006_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новий'), ('IN_WORK', 'В роботі'), ('SENT', 'Відправлено'), ('DELIVERED', 'Доставлено'), ('CANSELED', 'Відмінено'), ('DONE', 'Виконано')], default='NEW', max_length=9, verbose_name='Статус'),
        ),
    ]
