# Generated by Django 5.2.3 on 2025-07-03 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_shop', '0003_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Назва')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recommendations/', verbose_name='Зображення')),
                ('show', models.BooleanField(default=True, verbose_name='Показувати')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_shop.book', verbose_name='Книга')),
            ],
        ),
    ]
