# Generated by Django 5.2.3 on 2025-10-21 07:11

import core.orders.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_main', '0004_address_email_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(max_length=17, validators=[core.orders.validators.PhoneNumberValidator()], verbose_name='Телефон'),
        ),
    ]
