# Generated by Django 5.2.3 on 2025-07-14 12:55

import core.orders.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[core.orders.validators.PhoneNumberValidator(), django.core.validators.EmailValidator()], verbose_name="Ім'я"),
        ),
    ]
