# Generated by Django 5.2.3 on 2025-07-14 12:55

import core.orders.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_orders', '0002_alter_order_email_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[core.orders.validators.PhoneNumberValidator()], verbose_name="Ім'я"),
        ),
    ]
