# Generated by Django 5.2.3 on 2025-07-16 11:09

import core.orders.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_orders', '0003_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, validators=[core.orders.validators.PhoneNumberValidator()], verbose_name='Телефон'),
        ),
    ]
