# Generated by Django 5.2.3 on 2025-07-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_shop', '0005_alter_book_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othercharacteristic',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='other_characteristics',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='books', to='core_shop.othercharacteristic', verbose_name='Інші Характеристики'),
        ),
    ]
