# Generated by Django 5.2.3 on 2025-11-03 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_shop', '0007_othercharacteristic_unique_item_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='other_characteristics',
            field=models.ManyToManyField(blank=True, default=None, related_name='books', to='core_shop.othercharacteristic', verbose_name='Інші Характеристики'),
        ),
        migrations.AlterField(
            model_name='othercharacteristic',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core_shop.othercharacteristicitem', verbose_name='Характеристика'),
        ),
    ]
