FROM python:3.12-slim

RUN useradd -s /bin/sh -u 1234 nonroot

WORKDIR /usr/src/app

RUN apt update && apt install -y netcat-openbsd

RUN mkdir media

ENV PYTHONUNBUFFERED=1

ENV PYTHONDONTWRITEBYTECODE=1

RUN pip install --upgrade pip

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x /usr/src/app/entrypoint.prod.sh

ENTRYPOINT [ "./entrypoint.sh" ]
