# Generated by Django 5.2.3 on 2025-07-01 08:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=256, verbose_name='Слсаг')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('name', models.CharField(max_length=256, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Автори',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=256, verbose_name='Слсаг')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('cover', models.CharField(max_length=100, verbose_name='Обкладинка')),
            ],
            options={
                'verbose_name': 'Обкладинка',
                'verbose_name_plural': 'Обкладинки',
                'ordering': ['cover'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=256, verbose_name='Слсаг')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('language', models.CharField(max_length=100, verbose_name='Мова')),
            ],
            options={
                'verbose_name': 'Мова',
                'verbose_name_plural': 'Мови',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='OtherCharacteristicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва додаткової характеристики')),
            ],
            options={
                'verbose_name': 'Назва додаткової характеристики',
                'verbose_name_plural': 'Назви додаткових характеристик',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=256, verbose_name='Слсаг')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('name', models.CharField(max_length=256, verbose_name='Видавництво')),
            ],
            options={
                'verbose_name': 'Видавництво',
                'verbose_name_plural': 'Видавництва',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорію', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=256, verbose_name='Слсаг')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('title', models.CharField(max_length=256, verbose_name='Назва')),
                ('image', models.ImageField(blank=True, null=True, upload_to='books', verbose_name='Зображення')),
                ('isbn', models.CharField(max_length=20, verbose_name='ISBN')),
                ('description', models.TextField(verbose_name='Опис')),
                ('count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Залишок')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна')),
                ('discount', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Знижка')),
                ('author', models.ManyToManyField(related_name='books', to='core_shop.author')),
                ('cateogry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='core_shop.category', verbose_name='Категорія')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='core_shop.language', verbose_name='Мова')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='core_shop.publisher', verbose_name='Видавництво')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='OtherCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64, verbose_name='Значення характеристики')),
                ('books', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_characteristics', to='core_shop.book', verbose_name='Додаткові характеристики')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_shop.othercharacteristicitem', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Додаткова характеристика',
                'verbose_name_plural': 'Додаткові характеристики',
                'ordering': ['item'],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['id', 'slug'], name='core_shop_b_id_235a2b_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='core_shop_b_title_d33a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-created'], name='core_shop_b_created_16d808_idx'),
        ),
    ]
