# Generated by Django 5.2.3 on 2025-07-01 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_shop', '0002_author_cover_language_othercharacteristicitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': 'Автора', 'verbose_name_plural': 'Автори'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Книгу', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='cover',
            options={'ordering': ['cover'], 'verbose_name': 'Обкладинку', 'verbose_name_plural': 'Обкладинки'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['language'], 'verbose_name': 'Мову', 'verbose_name_plural': 'Мови'},
        ),
        migrations.AlterModelOptions(
            name='othercharacteristic',
            options={'ordering': ['item'], 'verbose_name': 'Додаткову характеристика', 'verbose_name_plural': 'Додаткові характеристики'},
        ),
        migrations.AlterModelOptions(
            name='othercharacteristicitem',
            options={'ordering': ['name'], 'verbose_name': 'Назву додаткової характеристики', 'verbose_name_plural': 'Назви додаткових характеристик'},
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book', to='core_shop.cover', verbose_name='Обкладинка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='core_shop.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='othercharacteristic',
            name='books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_characteristics', to='core_shop.book', verbose_name='Книга'),
        ),
    ]
