# Generated by Django 5.2.3 on 2025-07-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_shop', '0006_remove_othercharacteristic_books_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='othercharacteristic',
            constraint=models.UniqueConstraint(fields=('item', 'value'), name='unique_item_value'),
        ),
    ]
