# Generated by Django 5.2.3 on 2025-08-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_account', '0003_alter_user_options_user_is_sataff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_sataff',
            new_name='is_staff',
        ),
    ]
