# Generated by Django 5.2.3 on 2025-08-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_account', '0004_rename_is_sataff_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Адреса доставки'),
        ),
    ]
