# Generated by Django 5.2.3 on 2025-07-07 13:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Інформацію',
                'verbose_name_plural': 'Інформація',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='recommendations',
            options={'ordering': ['show', '-created'], 'verbose_name': 'Рекомендацію', 'verbose_name_plural': 'Рекомендації'},
        ),
    ]
