# Generated by Django 5.2.3 on 2025-10-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_main', '0005_alter_phone_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адресу', 'verbose_name_plural': 'Адреси'},
        ),
    ]
