#!/bin/sh

unset SECRET_KEY
unset DEBUG

unset DATABASE_HOST
unset DATABASE_PORT
unset POSTGRES_USER
unset POSTGRES_PASSWORD
unset POSTGRES_DB

unset CELERY_BROKER_URL

unset DEVELOP_EMAIL_SERVER
unset MAILDEV_WEB_HOST
unset MAILDEV_WEB_PORT

unset EMAIL_HOST
unset EMAIL_HOST_USER
unset EMAIL_HOST_PASSWORD
unset EMAIL_PORT
unset EMAIL_USE_TLS
# EMAIL_USE_SSL=1
unset DEFAULT_FROM_EMAIL

unset ALLOWED_HOSTS
unset CSRF_TRUSTED_ORIGINS