# Generated by Django 5.2.3 on 2025-08-04 11:15

import core.orders.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=20, validators=[core.orders.validators.PhoneNumberValidator()], verbose_name='Телефон')),
                ('first_name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=255, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=256, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('delivery_address', models.CharField(max_length=512, verbose_name='Адреса доставки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата створення')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата оновлення')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
