# Generated by Django 5.2.3 on 2025-08-04 11:26

import core.orders.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[core.orders.validators.PhoneNumberValidator()], verbose_name='Телефон'),
        ),
    ]
